spring:
    application:
        name: modern-employee-management-api
    jackson:
        serialization:
            indent-output: true
    datasource:
        username: "${DB_USERNAME}"
        url: "${DB_URL}"
        password: "${DB_PASSWORD}"
    jpa:
        hibernate:
            ddl-auto: update
        open-in-view: false
        show-sql: true
    threads:
        # Probably the most significant feature since Java 21+
        # Virtual threads!
        # See: https://pwrteams.com/content-hub/blog/modern-java-unleashed-virtual-threads-other-game-changing-features-in-jdk-21
        virtual:
            enabled: true